dist: trusty
sudo: required
language: go
go:
  - "1.11.x"
script:
  - go mod vendor
  - make build
  - make test
  - make vet
branches:
  only:
  - v2
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on

